subgraphs:
  products:
    routing_url: https://rover.apollo.dev/quickstart/products/graphql
    schema:
      file: ./products.graphql
  reviews:
    routing_url: https://rover.apollo.dev/quickstart/reviews/graphql
    schema:
      file: ./reviews.graphql
  books:
      routing_url: http://localhost:4003/graphql
      schema:
        file: ./books.graphql
  authors:
      routing_url: http://localhost:4004/graphql
      schema:
        file: ./authors.graphql
