subgraphs:
  books:
    # this is the unified book api
    routing_url: http://localhost:4008/graphql
    schema:
      file: ./books.graphql
  authors:
    routing_url: http://localhost:4004/graphql
    schema:
      file: ./author.graphql